<?php
// Error Levels Desciption
$locale['E_ERROR'] = "Fatal Errors halting script execution";
$locale['E_WARNING'] = "Non fatal Runtime Errors";
$locale['E_PARSE'] = "Error generated by parser";
$locale['E_NOTICE'] = "Run-time notices";
$locale['E_CORE_ERROR'] = "Error during PHP's initial startup";
$locale['E_CORE_WARNING'] = "Warning during PHP's initial startup";
$locale['E_COMPILE_ERROR'] = "Warning generated by zend";
$locale['E_COMPILE_WARNING'] = "Error generated by parser";
$locale['E_USER_ERROR'] = "Error generated by user using trigger_error() function";
$locale['E_USER_WARNING'] = "Warning generated by user using trigger_error() function";
$locale['E_USER_NOTICE'] = "Notice generated by user using trigger_error() function";
$locale['E_ALL'] = "Defines all messages except E_STRICT";
$locale['E_STRICT'] = "";
$locale['err_100'] = "نامشخص";
$locale['err_101'] = "<p><span style='color: #ff00ff;'><strong>هشدار:</strong> در بار خوانی این صفحه خطایی وجود دارد. لطفا با دقت خطا را بررسی و حل نمایید برای مشاهده خطای موجود در این صفحه به بخش  <a href='[ERROR_LOG_URL]'>خطاهای ورودی سایت  از اینجا</a> وارد شوید و سپس خطای این صفحه را حل کنید . اگر قادر به حل خطای این صفحه نیستید حتما خطای مذکور را<a href='http://www.php-fusion-iran.com' target='_blank'>از اینجا در سایت   رسمی فیوژن پارسی </a> مطرح نموده تا در اسرع وقت مشکل شما حل گردد ، توجه داشته باشید که خطای هایی که به صورت هوشمند به شما ابلاغ می گردد بایستی در اسرع وقت آنرا حل نمایید وگرنه ممکن است این خطاها سایت شما را با کندی مواجعه کند و یا یک مسله امنیتی گردد.<center> با تشکر از حسن انتخاب شما : سید بهروز آتش پیکر بناب مدیریت سایت رسمی فیوژن پارسی در ایران</span></center></p>";
?>