<?php
// Error Levels Desciption
$locale['E_ERROR'] = "Fatal Errors halting script execution";
$locale['E_WARNING'] = "Non fatal Runtime Errors";
$locale['E_PARSE'] = "Error generated by parser";
$locale['E_NOTICE'] = "Run-time notices";
$locale['E_CORE_ERROR'] = "Error during PHP's initial startup";
$locale['E_CORE_WARNING'] = "Warning during PHP's initial startup";
$locale['E_COMPILE_ERROR'] = "Warning generated by zend";
$locale['E_COMPILE_WARNING'] = "Error generated by parser";
$locale['E_USER_ERROR'] = "Error generated by user using trigger_error() function";
$locale['E_USER_WARNING'] = "Warning generated by user using trigger_error() function";
$locale['E_USER_NOTICE'] = "Notice generated by user using trigger_error() function";
$locale['E_ALL'] = "Defines all messages except E_STRICT";
$locale['E_STRICT'] = "";

$locale['err_100'] = "Ûํั ใสๆÝั";
$locale['err_101'] = "<strong>สอะํั:</strong> อีแ ฮุร รหไวม ลไิวม วแีÝอษ. ัฬวมก วไูั <a href='[ERROR_LOG_URL]'>ำฬแ วแรฮุวม</a> วแฮวี ศPHP-Fusion แแใาํฯ ใไ วแสÝวีํแ.";

// Error Managemetn
?>
